### ISSUE TITLE
Some questions about this code.

### ISSUE THREAD

**Issue by ZhJiaQi** [Justin900429/Facial-Graph-Representation-Learning#2]
The code you provided is very clear, but I would like to know if you have reproduced the results in the paper. If you do, how do you set the learning rate and the number of epoches?

**Comment by Justin900429** [comment]
To be honest, I failed to reproduce the results. I had contacted the authors but failed to get the right HP.
Also, the illustrations generated by the MagNet seem to be different in the paper.
I believe there are more details to be figured out.
