### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by sanjiaobo** [Justin900429/Facial-Graph-Representation-Learning#4]
Excuse me, When i  finished running the program，the accuracy is 0.38 in the tarin.log . (the epoch are 50)

So I want to ask about  your accuracy.

**Comment by Justin900429** [comment]
Hi,

I also screwed up when I trained by myself.
This reproduced code is not promising for getting the same accuracy 🥲 (may be wrong hyper-parameters or setting).

I would recommend contacting with the authors for getting the correct settings.
Thanks!
